### ISSUE TITLE
favicon is not transparent (maybe)

### ISSUE THREAD

**Issue by minge0n** [MC-Dashify/document#2]
<img alt="image" src="https://github.com/MC-Dashify/document/assets/56223465/2defe507-e1ae-473f-9d75-22c5b4e72f7a">

**Comment by pybsh** [comment]
Issue 감사합니다.  현재 수정했음을 알려드립니다. -> [[:bug: fix favicon]](https://github.com/MC-Dashify/document/commit/101a5ad38d5172c81a0ac51537f789f566184167)

![image](https://github.com/MC-Dashify/document/assets/59782214/22798bc4-eb0b-4bc9-98d4-46676e081b4a)
